# Generated by Django 3.1.2 on 2020-10-03 13:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('sorting_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
